 # 172.26.160.1
print('IPv4 adresa ovog računa je: 172.26.160.1')
prvi_bin = bin(172).replace('0b','')
drugi_bin = bin(26).replace('0b','')
treci_bin = bin(160).replace('0b','')
cetvrti_bin = bin(1).replace('0b','')
print(f'Binarni zapis IPv4 adrese je :',prvi_bin,'.', drugi_bin,'.',treci_bin,'.',cetvrti_bin, sep='')
prvi_oktet = oct(172).replace('0b','')
drugi_oktet = oct(26).replace('0b','')
treci_oktet = oct(160).replace('0b','')
cetvrti_oktet = oct(1).replace('0b','')
print(f'Oktalni zapis IPv4 adrese je :',prvi_oktet,'.', drugi_oktet,'.',treci_oktet,'.',cetvrti_oktet, sep='')
prvi_hextet = hex(172).replace('0b','')
drugi_hextet = hex(26).replace('0b','')
treci_hextet = hex(160).replace('0b','')
cetvrti_hextet = hex(1).replace('0b','')
print(f'Heksadekadski zapis IPv4 adrese je :',prvi_hextet,'.', drugi_hextet,'.',treci_hextet,'.',cetvrti_hextet, sep='')